language: python
python: 2.7
env:
    - TOX_ENV=py27-extras
    - TOX_ENV=py27-noextras
    - TOX_ENV=pypy-extras
    - TOX_ENV=pypy-noextras
    - TOX_ENV=py33-extras
    - TOX_ENV=py33-noextras
    - TOX_ENV=py34-extras
    - TOX_ENV=py34-noextras
    - TOX_ENV=py35-extras
    - TOX_ENV=py35-noextras

install:
    - sudo apt-get install graphviz
    - pip install tox coveralls

script:
    - tox -e $TOX_ENV

after_success:
    - tox -e coverage-report
    - coveralls
